# Generated by Django 4.1.5 on 2023-01-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrazyAudios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audios',
            new_name='Audio',
        ),
    ]
