# Generated by Django 4.1.5 on 2023-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrazyAudios', '0002_rename_audios_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
